require("freesec.settings")
require("freesec.lazy")
require("freesec.key_mappings")
require("freesec.utils")
require("freesec.autocmds")
require("freesec.plugins.init")
-- require("freesec.telescope-custom")
require("freesec.colorscheme")
