require("freesec.settings")
require("freesec.key_mappings")
require("freesec.utils")
require("freesec.autocmds")
require("freesec.lazy")
require("freesec.plugin_config.init")
-- require("freesec.colorscheme")
